name: easy_web_view
description: A super simple webview for Flutter Web, Mobile and Desktop
version: 1.6.0
homepage: https://github.com/rodydavis/easy_web_view
repository: https://github.com/rodydavis/plugins
maintainer: Rody Davis (@rodydavis)
environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_markdown: ^0.6.10+2
  flutter_widget_from_html: ^0.8.5
  html2md: ^1.2.6
  http: ^0.13.4
  markdown: ^5.0.0
  permission_handler: ^9.2.0
  url_launcher: ^6.1.3
  webview_flutter: ^3.0.4
  webview_windows: ^0.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0

flutter:
  uses-material-design: true
